### PR TITLE
Provide hint when user tries and fails to connect to localhost or…

### PR DESCRIPTION
**Pull request by CorgiMan**
…127.0.0.1.

### CODE REVIEW

**Comment by CorgiMan** [comment]
@uber/ringpop

**Comment by dansimau** [comment]
I would add a test for the case where we get a connect failed but we're not connecting to localhost.

**Comment by CorgiMan** [comment]
@dansimau Yeah, I don't want to connect to some random ip. Any ideas.
I tried connecting to 128.128.128.128:2999, and that gives a tchan timeout error. Not sure if I like that in the tests

**Comment by dansimau** [comment]
@CorgiMan Maybe "0.0.0.0:1"? But that will fail if there is anything listening on port 1. Or "0.0.0.0:0", but that will throw a slightly different error and may be platform dependent.

**Comment by jwolski** [comment]
lgtm

**Comment by thanodnl** [comment]
lgtm

**Pull request merged**
